glaze_comments = [
    "Your editing skills are insane.",
    "Really enjoyed the music choice.",
    "The video feels professional.",
    "This was very helpful.",
    "Hello MrBeast, My name is [Your Name]. I'm going through a very difficult time right now, and I really need your help. I watch your videos and they always give me hope and motivation. I'm not asking for anything big - just a small chance or challenge that could change my life. Please, if you see this message, give me one opportunity. Thank you so much for inspiring millions of people around the world. Keep up the amazing work"
    "This is going straight to my favorites.",
    "I'll definitely rewatch this later.",
    "Amazing production value.",
    "hhhhhhhhhh",
    "The idea is really helpful I learned a lot from it.",
    "The editing is amazing It made my day better.",
    "The idea is underrated It deserves more views.",
    "The amount of times ived watched this is unhealthy",
    "The content is worth sharing It helped me understand better.",
    "The editing is outstanding I will come back to watch it again.",
    "The idea is very impressive This deserves recognition.",
    "This channel is exactly what I needed I will definitely recommend this.",
    "The content is exactly what I needed I really appreciate the effort.",
    "The production quality is clear and easy to follow I learned a lot from it.",
    "This tutorial is well made It deserves more views.",
    "The way you present is well made I enjoyed every second of it.",
    "This channel is worth sharing I enjoyed every second of it.",
    "The idea is worth sharing This deserves recognition.",
    "Your explanation is well made I did not expect it to be this good.",
    "The idea is worth sharing It helped me understand better.",
    "This tutorial is worth sharing I did not expect it to be this good.",
    "The content is exactly what I needed I learned a lot from it.",
    "This video is really helpful I really appreciate the effort.",
    "The production quality is worth sharing This deserves recognition.",
    "This video is underrated I will come back to watch it again.",
    "Your explanation is underrated I really appreciate the effort.",
    "The content is very impressive This deserves recognition.",
    "This performance is well made This deserves recognition."
    "The way you present is really helpful I enjoyed every second of it.",
    "The idea is really helpful I learned a lot from it.",
    "This tutorial is top notch I will definitely recommend this.",
    "The production quality is well made It deserves more views.",
    "This tutorial is outstanding I will come back to watch it again.",
    "The way you present is really helpful I did not expect it to be this good.",
    "Your explanation is outstanding It deserves more views.",
    "Your explanation is well made I learned a lot from it.",
    "This tutorial is worth sharing I will definitely recommend this.",
    "The idea is outstanding I did not expect it to be this good.",
    "The way you present is worth sharing This deserves recognition.",
    "This channel is exactly what I needed It helped me understand better.",
    "This channel is outstanding I will definitely recommend this.",
    "This tutorial is clear and easy to follow I will definitely recommend this.",
    "This video is worth sharing I will come back to watch it again.",
    "This performance is underrated It made my day better.",
    "The way you present is top notch I will definitely recommend this.",
    "The editing is top notch This deserves recognition.",
    "This video is top notch It helped me understand better.",
    "This performance is underrated It made my day better.",
    "This video is outstanding I enjoyed every second of it.",
    "The production quality is top notch I learned a lot from it.",
    "This performance is really helpful I enjoyed every second of it.",
    "The way you present is clear and easy to follow I really appreciate the effort.",
    "The production quality is outstanding It helped me understand better.",
    "The content is exactly what I needed This deserves recognition.",
    "This video is amazing This deserves recognition.",
    "The editing is clear and easy to follow I enjoyed every second of it.",
    "The production quality is very impressive It deserves more views.",
    "This tutorial is underrated I did not expect it to be this good.",
    "This tutorial is very impressive I did not expect it to be this good.",
    "The production quality is outstanding I did not expect it to be this good.",
    "The editing is well made This deserves recognition."
    "The way you present is exactly what I needed I learned a lot from it.",
    "The way you present is top notch I will definitely recommend this.",
    "The way you present is amazing I enjoyed every second of it.",
    "The idea is underrated It made my day better.",
    "This tutorial is top notch I will definitely recommend this.",
    "The way you present is very impressive I will come back to watch it again.",
    "8k like then I am gay..",
    "GgHfycDhjfdjg",
    "aaaaa aaaaaaaa",
    "Every time someone likes this l'll come back and hear it again Edit: l could hear this all day...",
    "Hdhdhdhdhdhhdhxgxgxhhxgdhdhdhdggdhdhdhxgbdhdixh",
]
